// frontend/libs/user/ui/src/lib/Form/Checkbox.tsx
import React, { forwardRef, useId } from "react";
import { clsx } from "clsx";

export interface CheckboxProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, "type"> {
  label?: string;
  error?: string;
}

export const Checkbox = forwardRef<HTMLInputElement, CheckboxProps>(
  ({ label, error, className, disabled, ...props }, ref) => {
    const checkboxId = props.id || useId();
    return (
      <div className="flex flex-col gap-1">
        <div className="flex items-start gap-2">
          <input
            ref={ref}
            type="checkbox"
            className={clsx(
              "w-4 h-4 mt-0.5 rounded border-gray-300 text-blue-600",
              "focus:ring-2 focus:ring-blue-500 focus:ring-offset-0",
              "transition-all duration-200 cursor-pointer",
              disabled && "opacity-50 cursor-not-allowed",
              error && "border-red-500",
              className
            )}
            disabled={disabled}
            aria-invalid={!!error}
            aria-describedby={error ? `${checkboxId}-error` : undefined}
            {...props}
          />

          {label && (
            <label
              htmlFor={checkboxId}
              className={clsx(
                "text-sm text-gray-700 cursor-pointer select-none",
                disabled && "opacity-50 cursor-not-allowed"
              )}
            >
              {label}
            </label>
          )}
        </div>

        {error && (
          <p id={`${checkboxId}-error`} className="text-sm text-red-600 ml-6">
            {error}
          </p>
        )}
      </div>
    );
  }
);

Checkbox.displayName = "Checkbox";

// frontend/libs/admin/ui/src/lib/form/checkbox.component.ts
import { Component, Input, forwardRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ControlValueAccessor, NG_VALUE_ACCESSOR, FormsModule } from '@angular/forms';

@Component({
  selector: 'app-checkbox',
  standalone: true,
  imports: [CommonModule, FormsModule],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => CheckboxComponent),
      multi: true,
    },
  ],
  template: `
    <div class="flex flex-col gap-1">
      <div class="flex items-start gap-2">
        <input
          type="checkbox"
          [id]="checkboxId"
          [disabled]="disabled"
          [(ngModel)]="checked"
          (ngModelChange)="onValueChange($event)"
          (blur)="onTouched()"
          class="w-4 h-4 mt-0.5 rounded border-gray-600 bg-white/10 text-purple-600 focus:ring-2 focus:ring-purple-500 focus:ring-offset-0 transition-all duration-200 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
          [attr.aria-invalid]="error ? 'true' : null"
          [attr.aria-describedby]="error ? checkboxId + '-error' : null"
        />

        @if (label) {
          <label
            [for]="checkboxId"
            class="text-sm text-gray-200 cursor-pointer select-none"
            [class.opacity-50]="disabled"
            [class.cursor-not-allowed]="disabled"
          >
            {{ label }}
          </label>
        }
      </div>

      @if (error) {
        <p [id]="checkboxId + '-error'" class="text-sm text-red-400 ml-6">
          {{ error }}
        </p>
      }
    </div>
  `,
})
export class CheckboxComponent implements ControlValueAccessor {
  @Input() label = '';
  @Input() error = '';
  @Input() disabled = false;
  @Input() checkboxId = `checkbox-${Math.random().toString(36).substring(7)}`;

  checked = false;
  onChange: (value: boolean) => void = () => {};
  onTouched: () => void = () => {};

  onValueChange(value: boolean): void {
    this.checked = value;
    this.onChange(value);
  }

  writeValue(value: boolean): void {
    this.checked = value || false;
  }

  registerOnChange(fn: (value: boolean) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled = isDisabled;
  }
}
