// frontend/libs/user/ui/src/lib/Form/Textarea.tsx
import React, { forwardRef, useId } from "react";
import { clsx } from "clsx";

export interface TextareaProps
  extends React.TextareaHTMLAttributes<HTMLTextAreaElement> {
  label?: string;
  error?: string;
  helperText?: string;
  fullWidth?: boolean;
}

export const Textarea = forwardRef<HTMLTextAreaElement, TextareaProps>(
  (
    {
      label,
      error,
      helperText,
      fullWidth = false,
      className,
      disabled,
      ...props
    },
    ref
  ) => {
    const textareaId = props.id || useId();
    return (
      <div className={clsx("flex flex-col gap-1", fullWidth && "w-full")}>
        {label && (
          <label className="block text-sm font-medium text-gray-700">
            {label}
            {props.required && <span className="text-red-500 ml-1">*</span>}
          </label>
        )}

        <textarea
          ref={ref}
          className={clsx(
            "w-full px-4 py-2 border rounded-lg transition-all duration-200 resize-none",
            "focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent",
            error
              ? "border-red-500 focus:ring-red-500"
              : "border-gray-300 hover:border-gray-400",
            disabled && "bg-gray-100 cursor-not-allowed opacity-60",
            className
          )}
          disabled={disabled}
          aria-invalid={!!error}
          aria-describedby={
            [error ? `${textareaId}-error` : null, helperText && !error ? `${textareaId}-description` : null]
              .filter(Boolean)
              .join(' ') || undefined
          }
          {...props}
        />

        {error && (
          <p id={`${textareaId}-error`} role="alert" className="text-sm text-red-600">
            {error}
          </p>
        )}

        {helperText && !error && (
          <p id={`${textareaId}-description`} className="text-sm text-gray-500">{helperText}</p>
        )}
      </div>
    );
  }
);

Textarea.displayName = "Textarea";

// frontend/libs/admin/ui/src/lib/form/textarea.component.ts
import { Component, Input, forwardRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ControlValueAccessor, NG_VALUE_ACCESSOR, FormsModule } from '@angular/forms';

@Component({
  selector: 'app-textarea',
  standalone: true,
  imports: [CommonModule, FormsModule],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => TextareaComponent),
      multi: true,
    },
  ],
  template: `
    <div [class]="fullWidth ? 'w-full' : ''">
      @if (label) {
        <label [for]="textareaId" class="block text-sm font-medium text-gray-700 mb-1">
          {{ label }}
          @if (required) {
            <span class="text-red-400 ml-1">*</span>
          }
        </label>
      }

      <textarea
        [id]="textareaId"
        [placeholder]="placeholder"
        [disabled]="disabled"
        [required]="required"
        [rows]="rows"
        [(ngModel)]="value"
        (ngModelChange)="onValueChange($event)"
        (blur)="onTouched()"
        [class]="getTextareaClasses()"
        [attr.aria-invalid]="error ? 'true' : null"
        [attr.aria-describedby]="error ? textareaId + '-error' : (helperText ? textareaId + '-description' : null)"
      ></textarea>

      @if (error) {
        <p [id]="textareaId + '-error'" class="text-sm text-red-400 mt-1">
          {{ error }}
        </p>
      }

      @if (helperText && !error) {
        <p [id]="textareaId + '-description'" class="text-sm text-gray-500 mt-1">{{ helperText }}</p>
      }
    </div>
  `,
})
export class TextareaComponent implements ControlValueAccessor {
  @Input() label = '';
  @Input() placeholder = '';
  @Input() error = '';
  @Input() helperText = '';
  @Input() required = false;
  @Input() disabled = false;
  @Input() fullWidth = false;
  @Input() rows = 3;
  @Input() textareaId = `textarea-${Math.random().toString(36).substring(7)}`;

  value = '';
  onChange: (value: string) => void = () => {};
  onTouched: () => void = () => {};

  getTextareaClasses(): string {
    return [
      'w-full px-4 py-2.5 border rounded-lg transition-all duration-200 resize-none',
      'bg-white text-gray-900 placeholder-gray-400',
      'focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-purple-400',
      this.error ? 'border-red-500 focus:ring-red-500' : 'border-gray-200',
      this.disabled ? 'opacity-60 cursor-not-allowed' : '',
    ]
      .filter(Boolean)
      .join(' ');
  }

  onValueChange(value: string): void {
    this.value = value;
    this.onChange(value);
  }

  writeValue(value: string): void {
    this.value = value || '';
  }

  registerOnChange(fn: (value: string) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled = isDisabled;
  }
}
