// frontend/libs/admin/ui/src/lib/card/card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

export type CardVariant = 'default' | 'bordered' | 'elevated';
export type CardPadding = 'none' | 'sm' | 'md' | 'lg';

@Component({
  selector: 'app-card',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div [class]="getCardClasses()">
      <ng-content />
    </div>
  `,
})
export class CardComponent {
  @Input() variant: CardVariant = 'default';
  @Input() padding: CardPadding = 'md';

  private variantClasses: Record<CardVariant, string> = {
    default: 'bg-slate-800',
    bordered: 'bg-slate-800 border border-slate-700',
    elevated: 'bg-slate-800 shadow-lg hover:shadow-xl transition-shadow duration-200',
  };

  private paddingClasses: Record<CardPadding, string> = {
    none: '',
    sm: 'p-4',
    md: 'p-6',
    lg: 'p-8',
  };

  getCardClasses(): string {
    return [
      'rounded-lg',
      this.variantClasses[this.variant],
      this.paddingClasses[this.padding],
    ].join(' ');
  }
}

// frontend/libs/user/ui/src/lib/Card/Card.tsx
import React from "react";
import { clsx } from "clsx";

export interface CardProps extends React.HTMLAttributes<HTMLDivElement> {
  variant?: "default" | "bordered" | "elevated";
  padding?: "none" | "sm" | "md" | "lg";
  children: React.ReactNode;
}

const variantStyles = {
  default: "bg-white border border-gray-200 shadow-sm",
  bordered: "bg-white border border-gray-200",
  elevated: "bg-white shadow-md hover:shadow-lg transition-shadow duration-200 border border-gray-200",
};

const paddingStyles = {
  none: "",
  sm: "p-4",
  md: "p-6",
  lg: "p-8",
};

export const Card: React.FC<CardProps> = ({
  variant = "default",
  padding = "md",
  className,
  children,
  ...props
}) => {
  return (
    <div
      className={clsx(
        "rounded-xl",
        variantStyles[variant],
        paddingStyles[padding],
        className
      )}
      {...props}
    >
      {children}
    </div>
  );
};
