// frontend/libs/admin/ui/src/lib/form/switch.component.ts
import { Component, Input, forwardRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ControlValueAccessor, NG_VALUE_ACCESSOR, FormsModule } from '@angular/forms';

@Component({
  selector: 'app-switch',
  standalone: true,
  imports: [CommonModule, FormsModule],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => SwitchComponent),
      multi: true,
    },
  ],
  template: `
    <div class="flex items-center gap-3">
      <label class="relative inline-flex items-center cursor-pointer">
        <input
          type="checkbox"
          [disabled]="disabled"
          [(ngModel)]="checked"
          (ngModelChange)="onValueChange($event)"
          (blur)="onTouched()"
          class="sr-only peer"
        />
        <div
          class="w-11 h-6 rounded-full transition-colors duration-200 peer-focus:ring-2 peer-focus:ring-purple-500 peer-focus:ring-offset-2"
          [class.bg-purple-600]="checked"
          [class.bg-gray-300]="!checked"
          [class.opacity-50]="disabled"
          [class.cursor-not-allowed]="disabled"
        >
          <div
            class="absolute top-0.5 left-0.5 bg-white w-5 h-5 rounded-full transition-transform duration-200"
            [class.translate-x-5]="checked"
          ></div>
        </div>
      </label>

      @if (label) {
        <span
          class="text-sm text-gray-800"
          [class.opacity-50]="disabled"
          [class.cursor-not-allowed]="disabled"
        >
          {{ label }}
        </span>
      }
    </div>
  `,
})
export class SwitchComponent implements ControlValueAccessor {
  @Input() label = '';
  @Input() disabled = false;

  checked = false;
  onChange: (value: boolean) => void = () => {};
  onTouched: () => void = () => {};

  onValueChange(value: boolean): void {
    this.checked = value;
    this.onChange(value);
  }

  writeValue(value: boolean): void {
    this.checked = value || false;
  }

  registerOnChange(fn: (value: boolean) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    this.disabled = isDisabled;
  }
}

// frontend/libs/user/ui/src/lib/Form/Switch.tsx
import React, { forwardRef } from "react";
import { clsx } from "clsx";

export interface SwitchProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, "type"> {
  label?: string;
  error?: string;
}

export const Switch = forwardRef<HTMLInputElement, SwitchProps>(
  ({ label, error, className, disabled, checked, ...props }, ref) => {
    return (
      <div className="flex flex-col gap-1">
        <div className="flex items-center gap-3">
          <label className="relative inline-flex items-center cursor-pointer">
            <input
              ref={ref}
              type="checkbox"
              checked={checked}
              className="sr-only peer"
              disabled={disabled}
              aria-invalid={!!error}
              aria-describedby={error ? `${props.id}-error` : undefined}
              {...props}
            />
            <div
              className={clsx(
                "w-11 h-6 rounded-full transition-colors duration-200",
                "peer-focus:ring-2 peer-focus:ring-blue-500 peer-focus:ring-offset-2",
                checked ? "bg-blue-600" : "bg-gray-300",
                disabled && "opacity-50 cursor-not-allowed",
                error && "ring-2 ring-red-500",
                className
              )}
            >
              <div
                className={clsx(
                  "absolute top-0.5 left-0.5 bg-white w-5 h-5 rounded-full transition-transform duration-200",
                  checked && "transform translate-x-5"
                )}
              />
            </div>
          </label>

          {label && (
            <span
              className={clsx(
                "text-sm text-gray-700",
                disabled && "opacity-50 cursor-not-allowed"
              )}
            >
              {label}
            </span>
          )}
        </div>

        {error && (
          <p id={`${props.id}-error`} className="text-sm text-red-600">
            {error}
          </p>
        )}
      </div>
    );
  }
);

Switch.displayName = "Switch";
